### ISSUE TITLE
Unknown model file format version with Yolo Model Object Detection

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Labs-IntelligentAPIs#3]
"The parameter is incorrect.\r\n\r\nFailed to load model with error: Unknown model file format version."

```
   at CommunityToolkit.Labs.Intelligent.ObjectDetection.YOLOObjectDetector.<InitModelAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityToolkit.Labs.Intelligent.ObjectDetection.YOLOObjectDetector.<EvaluateFrame>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityToolkit.Labs.Intelligent.ObjectDetection.YOLOObjectDetector.<DetectObjects>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityToolkit.Labs.Intelligent.ObjectDetection.YOLOObjectDetector.<DetectObjects>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IntelligentLabsTest.ResultsPage.<OnNavigatedTo>d__4.MoveNext() in H:\code\Labs-IntelligentAPIs\IntelligentAPIsTester\ResultsPage.xaml.cs:line 74
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

Happens for me in main and with NuGet package.

VS 16.9.8
Win 10 21H1 19043

**Comment by michael-hawker** [comment]
Happens on this line:
```
_session = new LearningModelSession(_model, device);
```

```
   at Windows.AI.MachineLearning.LearningModelSession..ctor(LearningModel model, LearningModelDevice deviceToRunOn)
   at CommunityToolkit.Labs.Intelligent.ObjectDetection.YOLOObjectDetector.<InitModelAsync>d__9.MoveNext() in H:\code\Labs-IntelligentAPIs\ObjectDetector\YOLOObjectDetector.cs:line 191
```

**Comment by michael-hawker** [comment]
This happens for me in [their official sample](https://github.com/microsoft/Windows-Machine-Learning/tree/master/Samples/Tutorial%20Samples/YOLOv4ObjectDetection) as well:

![image](https://user-images.githubusercontent.com/24302614/128232857-d49fca49-7765-4304-af19-7755176e8cf1.png)

**Comment by michael-hawker** [comment]
Linking to issue in the [sample repo here](https://github.com/microsoft/Windows-Machine-Learning/issues/404).
